services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_USER_SERVICE_URL=http://localhost:4000
      - NEXT_PUBLIC_TODO_SERVICE_URL=http://localhost:4001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
