version: "3.8"

services:
  todo-db:
    image: postgres:15
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  todo-service:
    build: .
    env_file:
      - .env
    depends_on:
      - todo-db
    ports:
      - "4001:4001"

volumes:
  todo-db-data:
